CompanyInfoApp/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CompanyInfoApp.Models
{
    public class Company
    {
        [Key]
        public Int64 CompanyId { get; set; }
        [Required(ErrorMessage = "Company Name Required")]
        [DisplayName("Company Name")]
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Invalid Email Address")]
        [DisplayName("Email Id")]
        public string EmailId { get; set; }
    }
}

CompanyInfoApp/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyInfoApp.Models;
using CompanyInfoApp.ViewModel;

namespace CompanyInfoApp.Controllers
{
    public class CompaniesController : Controller
    {
        private DatabaseDbContext db = new DatabaseDbContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.CompanyDbSet.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var companyInfo = (from m in db.CompanyDbSet
                               join n in db.CustomPropertyDbSet on m.CompanyId equals n.CompanyId
                               where m.CompanyId == id
                               select new ViewCompany()
                               {
                                   CompanyId = m.CompanyId,
                                   CompanyName = m.CompanyName,
                                   Address = m.Address,
                                   EmailId = m.EmailId,
                                   Website = m.Website,
                                   CustomPro = n.CustomPro,
                                   Type = n.Type,
                                   Value = n.Value,
                                   IsEnable = n.IsEnable
                               }).ToList();

            if (companyInfo == null)
            {
                return HttpNotFound();
            }
            ViewBag.companyInfo = companyInfo;
            return View(companyInfo.FirstOrDefault());
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyId,CompanyName,Address,Website,EmailId")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.CompanyDbSet.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.CompanyDbSet.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,CompanyName,Address,Website,EmailId")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyInfoApp/Controllers/CustomPropertiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyInfoApp.Models;

namespace CompanyInfoApp.Controllers
{
    public class CustomPropertiesController : Controller
    {
        private DatabaseDbContext db = new DatabaseDbContext();

        // GET: CustomProperties/Create
        public ActionResult Create(long? CompanyId)
        {
            if (CompanyId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CustomPropertyList = db.CustomPropertyDbSet.Where(c => c.CompanyId == CompanyId).ToList();
            CustomProperty customProperty = new CustomProperty();
            customProperty.CompanyId = (long)CompanyId;
            return View(customProperty);
        }

        // POST: CustomProperties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CompanyId,CustomPro,Type,Value,IsEnable")] CustomProperty customProperty)
        {
            if (ModelState.IsValid)
            {
                db.CustomPropertyDbSet.Add(customProperty);
                db.SaveChanges();

                ViewBag.CustomPropertyList = db.CustomPropertyDbSet.Where(c => c.CompanyId == customProperty.CompanyId).ToList();
                return RedirectToAction("Create", new { CompanyId = customProperty.CompanyId });
            }

            ViewBag.CustomPropertyList = db.CustomPropertyDbSet.Where(c => c.CompanyId == customProperty.CompanyId).ToList();
            return View(customProperty);
        }

        // GET: CustomProperties1/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomProperty customProperty = db.CustomPropertyDbSet.Find(id);
            if (customProperty == null)
            {
                return HttpNotFound();
            }

            return View(customProperty);
        }

        // POST: CustomProperties1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CompanyId,CustomPro,Type,Value,IsEnable")] CustomProperty customProperty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customProperty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create", new { CompanyId = customProperty.CompanyId });
            }

            return View(customProperty);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyInfoApp/Views/Companies/Create.cshtml
@model CompanyInfoApp.Models.Company

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompanyInfoApp/Views/Companies/Details.cshtml
@model CompanyInfoApp.ViewModel.ViewCompany

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>
        @foreach (var item in ViewBag.companyInfo as List<CompanyInfoApp.ViewModel.ViewCompany>)
        {
            if (item.IsEnable)
            {
                <dt>
                    @item.CustomPro
                </dt>
                <dd>
                    @item.Value
                </dd>
            }

        }

    </dl>
</div>
<p>
</p>

CompanyInfoApp/Views/Companies/Edit.cshtml
@model CompanyInfoApp.Models.Company

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyId)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Add custom properties", "Create", "CustomProperties", new { CompanyId = Model.CompanyId },null)
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompanyInfoApp/Views/Companies/Index.cshtml
@model IEnumerable<CompanyInfoApp.Models.Company>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.CompanyId }) |
            @Html.ActionLink("Details", "Details", new { id = item.CompanyId })@* |
        @Html.ActionLink("Delete", "Delete", new { id=item.CompanyId })*@
        </td>
    </tr>
}

</table>